language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - PROFILE=non-existant
    - PROFILE=spring5-next


cache:
  directories:
    - $HOME/.m2

os:
  - linux

branches:
  except:
    - gh-pages
    
sudo: false
script:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ]; then
  -   mvn -Pdistribute,snapshot,docs clean deploy
  - else
  -   mvn clean dependency:list test -P${PROFILE} -Dsort
  - fi