language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - PROFILE=non-existant
    - PROFILE=spring5-next


cache:
  directories:
    - $HOME/.m2

os:
  - linux
  - osx

sudo: false
script: "mvn clean dependency:list test -P${PROFILE} -Dsort"